name: slide_puzzle

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: 2.6.0-5.2.pre

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.1

dev_dependencies:
  flutter_lints: ^1.0.4
  flutter_test:
    sdk: flutter
  test: ^1.17.12

flutter:
  uses-material-design: true
  assets:
    - asset/

  fonts:
    - family: Plaster
      fonts:
        - asset: asset/fonts/plaster/Plaster-Regular.ttf
